version: '3.3'
services:
  mysqldb:
    hostname: mysqldb
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - files/.env.drupal-ide
    ports:
      - '3306:3306'
  drupal:
    stdin_open: true
    tty: true
    image: davefletcher/drupal-ide
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ${PWD}:/workspace
    restart: always
    env_file:
      - files/.env.drupal-ide
    depends_on:
      - mysqldb
