version: '3.3'
services:
  drupal:
    stdin_open: true
    tty: true
    image: davefletcher/drupal-devcontainer
    #build:
    #  context: ..
    #  dockerfile: .devcontainer/Dockerfile
    ports:
      - 80:80
      - 9000:9000
    volumes:
      - ${PWD}:/workspace
    restart: always
