version: '3.3'
services:
  drupal:
    stdin_open: true
    tty: true
    image: davefletcher/drupal-devcontainer
    #build:
    #  context: ..
    #  dockerfile: .devcontainer/Dockerfile
    ports:
      - 80:80
      - 9000:9000
    volumes:
      - ${PWD}:/workspace
      - ${PWD}/.base/features:/var/www/html/web/modules/custom_base_features
      - ${PWD}/.base/modules:/var/www/html/web/modules/custom_base
      - ${PWD}/.base/themes:/var/www/html/web/themes/custom_base_themes
      - ${PWD}/features:/var/www/html/web/modules/custom_features
      - ${PWD}/modules:/var/www/html/web/modules/custom
      - ${PWD}/themes:/var/www/html/web/themes/custom_themes
      - ${PWD}/composer.json:/var/www/html/composer.json
    restart: always

#  varnish:
#    image: wodby/drupal-varnish:4.1-2.1.2
#    ports:
#      - 80:6081
#    depends_on:
#      - drupal
#    environment:
#      VARNISH_SECRET: secret
#      VARNISH_BACKEND_HOST: drupal
#      VARNISH_BACKEND_PORT: 80
#      VARNISH_CONFIG_PRESET: drupal
#      VARNISH_PURGE_EXTERNAL_REQUEST_HEADER: X-Real-IP
#    labels:
#      - 'traefik.backend=varnish'
#      - 'traefik.port=6081'
#      - "traefik.frontend.rule=Host:varnish.${COMPOSE_PROJECT_NAME}.docker.localhost"

